server:
    port: 8084
spring:
    application:
        name: lhtregistry
lhtregistry:
    serverList:
        - http://127.0.0.1:8084
        - http://127.0.0.1:8085
        - http://127.0.0.1:8086

logging:
    level:
        root: info
        io.github.lhtforit: debug
